### ISSUE TITLE
Error: Unable to parse color from string: 

### ISSUE THREAD

**Issue by ravelijnhollander** [egodact/egodact-issues#1]
Bij deze leerling kan ik niet bij zijn challenges kijken. Dit geeft een foutmelding. Refreshen en uitloggen en opnieuw aanmelden lukt niet. Ook de leerling zelf had geen toegang.

Bij andere leerlingen tot nu toe wel.

Foutmeldeing:
Er is iets fout gegaan
Er is een fout opgetreden die bij ons onbekend is. Probeer de pagina te refreshen. Als dat niet werkt, probeer uit te loggen met de knop hieronder als je nog ingelogd bent.

**Comment by rafaelklaessen** [comment]
Beste Pim,

Dankjewel voor je bericht! Deze fout is bij mij bekend; dit weekend komt er een fix online.

Dankjewel,
Rafael

**Comment by rafaelklaessen** [comment]
Fix staat online :)
