### ISSUE TITLE
mr chadd logo laat zich niet zien (fix in issue) #challengemonitor 

### ISSUE THREAD

**Issue by BananaChad** [egodact/egodact-issues#2]
Dus voor een tijdje staat er bij een challenge van een leerling zo'n mr chadd knop die naar de website gaat, het logo van mr chadd was verplaatst naar een andere link en nu laat het niet het logo zien maar laat het 
<img alt="Link button icon" src="https://www.mrchadd.nl/wp-content/uploads/2019/01/MrChadd_geel_rond.png" class="styles-hy1ztb"> zien, een fix hiervoor is om naar het mrchadd website te gaan, naar beneden scrollen en dan zie je het logo van mr chadd, daarna kan je in inspect element om te kijken waar het logo bestand vandaan komt. Degene die in de challenge monitor staat is https://www.mrchadd.nl/wp-content/uploads/2019/01/MrChadd_geel_rond.pnghy1ztb
de foto was vroeger wel op de mr chadd website maar is verplaatst naar https://d33wubrfki0l68.cloudfront.net/188a62f11255c7d4af804e7b9a965b5dde0d0299/ddb94/img/footer-logo.svg
als je deze link vervangt met die andere ziet het er weer normaal uit (wordt klein genoeg bij de website
<img src="https://d33wubrfki0l68.cloudfront.net/188a62f11255c7d4af804e7b9a965b5dde0d0299/ddb94/img/footer-logo.svg" alt="logo">
of de andere logo (werkt ook transparant bij de challengemonitor)
<img alt="Link button icon" src="https://cdn.mrchadd.nl/ui-components/img/logo-black-on-transparent.svg" class="styles-hy1ztb"> (is beter te zien op een licht gekleurde achtergrond)

om dit na te checken/fixen(?) kan je mijn stappen gebruiken om de link te vinden van de mr chadd logo

Voor:
![image](https://user-images.githubusercontent.com/105674111/193836126-0ae8a3dd-a277-4429-ae73-7428e3433308.png)
logo link vinden (2 logos op website):
![image](https://user-images.githubusercontent.com/105674111/193836570-33623159-17d0-42b2-b7ed-dea99077b681.png)
![image](https://user-images.githubusercontent.com/105674111/193836672-ef6f157c-1894-4833-a4cd-383887911b16.png)
Na die link in de challenge monitor doen (2 logos):
![image](https://user-images.githubusercontent.com/105674111/193836888-cb6cfec6-9868-4a62-80eb-d767d25039b2.png)
![image](https://user-images.githubusercontent.com/105674111/193837362-723ed6db-678c-4bb2-902c-a2dce35915be.png)

**Comment by rafaelklaessen** [comment]
Hoi, dankjewel voor je issue. Ik heb 'm geüpdatet naar de nieuwe afbeeldingslocatie. De zwarte versie van het logo kan ik niet gebruiken omdat ie niet zichtbaar is als CM in dark mode staat, dus ik heb de gele gekozen.
